### ISSUE TITLE
PCF85714.h

### ISSUE THREAD

**Issue by Muhammad-Adnan-Ahmed** [adafruit/Adafruit_PCF8574#5]
PC85714. h  contain only one I/O extender address. How could be add more I/O extender with header file. 
Please guide. 

#ifndef _ADAFRUIT_PCF8574_H
#define _ADAFRUIT_PCF8574_H

#include "Arduino.h"
#include <Adafruit_BusIO_Register.h>
#include <Adafruit_I2CDevice.h>

#define PCF8574_I2CADDR_DEFAULT 0x20

/*!
 *    @brief  Class that stores state and functions for interacting with
 *            the PCF8574 I2C Expander
 */
class Adafruit_PCF8574 {
public:
  Adafruit_PCF8574();
  bool begin(uint8_t i2c_addr = PCF8574_I2CADDR_DEFAULT, TwoWire *wire = &Wire);

  bool digitalWriteByte(uint8_t d);
  bool digitalWrite(uint8_t pinnum, bool val);
  uint8_t digitalReadByte(void);
  bool digitalRead(uint8_t pinnum);
  bool pinMode(uint8_t pinnum, uint8_t val);

private:
  uint8_t _readbuf = 0, _writebuf = 0;

  Adafruit_I2CDevice *i2c_dev;
};

#endif

**Comment by caternuson** [comment]
That is just defining a default address. For any other address, pass it in when calling begin:
https://github.com/adafruit/Adafruit_PCF8574/blob/d6588ad29a11db8cd3119b243d7c1ba6da2f0cca/Adafruit_PCF8574.h#L33

Ex:
```cpp
pcf.begin(0x21);
```

**Comment by caternuson** [comment]
Closing. The above post should be the answer. If there was more to the issue, please provide more details and the issue can be reopened.
